# Generated by Django 2.2 on 2020-02-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200201_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupon',
            name='valid',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
