# Generated by Django 2.2 on 2020-02-02 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200202_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_cupon',
            old_name='times_left',
            new_name='times_used',
        ),
    ]
