# Generated by Django 2.2 on 2020-02-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200202_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupon',
            name='Global',
            field=models.BooleanField(default=True),
        ),
    ]
