# Generated by Django 2.2 on 2020-02-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_cupon_global'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_cupon',
            name='times_used',
            field=models.IntegerField(default=0),
        ),
    ]
